### ISSUE TITLE
Improve set up guide

### ISSUE THREAD

**Issue by DavidRG13** [honorem/spring-session-cassandra#2]
Probably I am missing something but, I followed the instructions and it's not working.
I'm not using Spring data Cassandra yet, so the first thing I am going to store in there is the session objects. I guess some cassandra configuration is missing for this to work, right?

BTW, I can't see any errors, just "application failed to start"

Thanks you!

**Comment by honorem** [comment]
Hi David,

The only configuration you need in order to make this work is to have a
class implementing AbstractCassandraConfiguration.

Sorry that i can't help you more. Do you have a sample of code that can
reproduce the error?

Marc

2017-08-02 11:18 GMT+02:00 David Rodriguez Gonzalez <
notifications@github.com>:

**Comment by DavidRG13** [comment]
Hi @honorem ,

We managed to find the issue, incompatibility between Spring, Spring Data and Cassandra driver versions. Sadly we have to implement it manually :(

Thanks a lot for your help!

Closing this as it's not an issue
